import type { ASRSQuestion } from "./types";

export const ASRS_PART_A_HIGH_RISK_THRESHOLD = 4;

export const asrsQuestions: ASRSQuestion[] = [
  {
    id: "asrs_1",
    questionNumber: 1,
    part: "A",
    domain: "Inattention",
    text: "How often do you have trouble wrapping up the final details of a project, once the challenging parts have been done?",
    shadedThreshold: [2, 3, 4],
  },
  {
    id: "asrs_2",
    questionNumber: 2,
    part: "A",
    domain: "Inattention",
    text: "How often do you have difficulty getting things in order when you have to do a task that requires organization?",
    shadedThreshold: [2, 3, 4],
  },
  {
    id: "asrs_3",
    questionNumber: 3,
    part: "A",
    domain: "Inattention",
    text: "How often do you have problems remembering appointments or obligations?",
    shadedThreshold: [2, 3, 4],
  },
  {
    id: "asrs_4",
    questionNumber: 4,
    part: "A",
    domain: "Inattention",
    text: "When you have a task that requires a lot of thought, how often do you avoid or delay getting started?",
    shadedThreshold: [3, 4],
  },
  {
    id: "asrs_5",
    questionNumber: 5,
    part: "A",
    domain: "Hyperactivity",
    text: "How often do you fidget or squirm with your hands or feet when you have to sit down for a long time?",
    shadedThreshold: [3, 4],
  },
  {
    id: "asrs_6",
    questionNumber: 6,
    part: "A",
    domain: "Hyperactivity",
    text: "How often do you feel overly active and compelled to do things, like you were driven by a motor?",
    shadedThreshold: [3, 4],
  },
  {
    id: "asrs_7",
    questionNumber: 7,
    part: "B",
    domain: "Inattention",
    text: "How often do you make careless mistakes when you have to work on a boring or difficult project?",
    shadedThreshold: [2, 3, 4],
  },
  {
    id: "asrs_8",
    questionNumber: 8,
    part: "B",
    domain: "Inattention",
    text: "How often do you have difficulty keeping your attention when you are doing boring or repetitive work?",
    shadedThreshold: [2, 3, 4],
  },
  {
    id: "asrs_9",
    questionNumber: 9,
    part: "B",
    domain: "Inattention",
    text: "How often do you have difficulty concentrating on what people say to you, even when they are speaking to you directly?",
    shadedThreshold: [2, 3, 4],
  },
  {
    id: "asrs_10",
    questionNumber: 10,
    part: "B",
    domain: "Inattention",
    text: "How often do you misplace or have difficulty finding things at home or at work?",
    shadedThreshold: [3, 4],
  },
  {
    id: "asrs_11",
    questionNumber: 11,
    part: "B",
    domain: "Inattention",
    text: "How often are you distracted by activity or noise around you?",
    shadedThreshold: [3, 4],
  },
  {
    id: "asrs_12",
    questionNumber: 12,
    part: "B",
    domain: "Hyperactivity",
    text: "How often do you leave your seat in meetings or other situations in which you are expected to remain seated?",
    shadedThreshold: [2, 3, 4],
  },
  {
    id: "asrs_13",
    questionNumber: 13,
    part: "B",
    domain: "Hyperactivity",
    text: "How often do you feel restless or fidgety?",
    shadedThreshold: [3, 4],
  },
  {
    id: "asrs_14",
    questionNumber: 14,
    part: "B",
    domain: "Hyperactivity",
    text: "How often do you have difficulty unwinding and relaxing when you have time to yourself?",
    shadedThreshold: [3, 4],
  },
  {
    id: "asrs_15",
    questionNumber: 15,
    part: "B",
    domain: "Hyperactivity",
    text: "How often do you find yourself talking too much when you are in social situations?",
    shadedThreshold: [3, 4],
  },
  {
    id: "asrs_16",
    questionNumber: 16,
    part: "B",
    domain: "Hyperactivity",
    text: "When you're in a conversation, how often do you find yourself finishing the sentences of the people you are talking to?",
    shadedThreshold: [2, 3, 4],
  },
  {
    id: "asrs_17",
    questionNumber: 17,
    part: "B",
    domain: "Hyperactivity",
    text: "How often do you have difficulty waiting your turn in situations when turn taking is required?",
    shadedThreshold: [3, 4],
  },
  {
    id: "asrs_18",
    questionNumber: 18,
    part: "B",
    domain: "Hyperactivity",
    text: "How often do you interrupt others when they are busy?",
    shadedThreshold: [2, 3, 4],
  },
];
