import type { DSM5Question } from "./types";

export const dsm5Questions: DSM5Question[] = [
  // Domain A: Inattention (15 questions)
  {
    id: "dsm5_a1",
    domain: "A",
    domainName: "Inattention",
    questionNumber: 1,
    text: "Failing to give close attention to details or making careless mistakes in work, school, or other activities",
    helpText: "e.g., overlooking errors in documents, rushing through tasks",
    clinicalThreshold: 3,
  },
  {
    id: "dsm5_a2",
    domain: "A",
    domainName: "Inattention",
    questionNumber: 2,
    text: "Having difficulty sustaining attention during tasks or activities",
    helpText: "e.g., losing focus during meetings, lectures, or lengthy reading",
    clinicalThreshold: 3,
  },
  {
    id: "dsm5_a3",
    domain: "A",
    domainName: "Inattention",
    questionNumber: 3,
    text: "Not seeming to listen when spoken to directly",
    helpText: "e.g., mind appears elsewhere even without obvious distraction",
    clinicalThreshold: 3,
  },
  {
    id: "dsm5_a4",
    domain: "A",
    domainName: "Inattention",
    questionNumber: 4,
    text: "Failing to follow through on instructions and not finishing tasks",
    helpText: "e.g., starting tasks but quickly getting sidetracked",
    clinicalThreshold: 3,
  },
  {
    id: "dsm5_a5",
    domain: "A",
    domainName: "Inattention",
    questionNumber: 5,
    text: "Having difficulty organizing tasks and activities",
    helpText: "e.g., struggling to manage sequential tasks, deadlines, or materials",
    clinicalThreshold: 3,
  },
  {
    id: "dsm5_a6",
    domain: "A",
    domainName: "Inattention",
    questionNumber: 6,
    text: "Avoiding or being reluctant to engage in tasks requiring sustained mental effort",
    helpText: "e.g., preparing reports, completing forms, reviewing documents",
    clinicalThreshold: 3,
  },
  {
    id: "dsm5_a7",
    domain: "A",
    domainName: "Inattention",
    questionNumber: 7,
    text: "Losing things necessary for tasks or activities",
    helpText: "e.g., misplacing keys, phone, wallet, tools, paperwork",
    clinicalThreshold: 3,
  },
  {
    id: "dsm5_a8",
    domain: "A",
    domainName: "Inattention",
    questionNumber: 8,
    text: "Being easily distracted by unrelated thoughts or stimuli",
    helpText: "e.g., noticing unrelated things mid-task, mind wandering",
    clinicalThreshold: 3,
  },
  {
    id: "dsm5_a9",
    domain: "A",
    domainName: "Inattention",
    questionNumber: 9,
    text: "Being forgetful in daily activities",
    helpText: "e.g., missing appointments, forgetting errands or chores",
    clinicalThreshold: 3,
  },
  {
    id: "dsm5_a10",
    domain: "A",
    domainName: "Inattention",
    questionNumber: 10,
    text: "Starting many tasks but rarely finishing them before moving on to something else",
    helpText: "e.g., half-completed projects, abandoned hobbies",
    clinicalThreshold: 3,
  },
  {
    id: "dsm5_a11",
    domain: "A",
    domainName: "Inattention",
    questionNumber: 11,
    text: "Losing track of time or underestimating how long tasks will take",
    helpText: "e.g., consistently running late, missing deadlines unexpectedly",
    clinicalThreshold: 3,
  },
  {
    id: "dsm5_a12",
    domain: "A",
    domainName: "Inattention",
    questionNumber: 12,
    text: "Having difficulty reading or following long documents without re-reading multiple times",
    helpText: "e.g., not retaining written information, needing to reread paragraphs",
    clinicalThreshold: 3,
  },
  {
    id: "dsm5_a13",
    domain: "A",
    domainName: "Inattention",
    questionNumber: 13,
    text: "Missing important details in conversations or instructions",
    helpText: "e.g., forgetting key parts of what someone said shortly after",
    clinicalThreshold: 3,
  },
  {
    id: "dsm5_a14",
    domain: "A",
    domainName: "Inattention",
    questionNumber: 14,
    text: "Feeling mentally exhausted after tasks that require concentration",
    helpText: "e.g., even moderate focus demands feel disproportionately draining",
    clinicalThreshold: 3,
  },
  {
    id: "dsm5_a15",
    domain: "A",
    domainName: "Inattention",
    questionNumber: 15,
    text: "Having trouble returning to a task after being interrupted",
    helpText: "e.g., difficulty re-engaging or remembering where you left off",
    clinicalThreshold: 3,
  },

  // Domain B: Hyperactivity/Impulsivity (15 questions)
  {
    id: "dsm5_b1",
    domain: "B",
    domainName: "Hyperactivity/Impulsivity",
    questionNumber: 16,
    text: "Fidgeting with or tapping hands or feet, or squirming in your seat",
    helpText: "e.g., drumming fingers, shaking leg, shifting constantly",
    clinicalThreshold: 3,
  },
  {
    id: "dsm5_b2",
    domain: "B",
    domainName: "Hyperactivity/Impulsivity",
    questionNumber: 17,
    text: "Leaving your seat when remaining seated is expected",
    helpText: "e.g., getting up in meetings, classrooms, or during meals",
    clinicalThreshold: 3,
  },
  {
    id: "dsm5_b3",
    domain: "B",
    domainName: "Hyperactivity/Impulsivity",
    questionNumber: 18,
    text: "Feeling restless — a persistent internal sense of 'needing to move'",
    helpText: "e.g., feels uncomfortable sitting still for extended periods",
    clinicalThreshold: 3,
  },
  {
    id: "dsm5_b4",
    domain: "B",
    domainName: "Hyperactivity/Impulsivity",
    questionNumber: 19,
    text: "Being unable to engage in leisure activities quietly",
    helpText: "e.g., difficulty watching a film, reading, or relaxing without doing something else",
    clinicalThreshold: 3,
  },
  {
    id: "dsm5_b5",
    domain: "B",
    domainName: "Hyperactivity/Impulsivity",
    questionNumber: 20,
    text: "Feeling 'on the go' or driven, as if 'powered by a motor'",
    helpText: "e.g., others find it hard to keep up, or you feel unable to slow down",
    clinicalThreshold: 3,
  },
  {
    id: "dsm5_b6",
    domain: "B",
    domainName: "Hyperactivity/Impulsivity",
    questionNumber: 21,
    text: "Talking excessively in conversations",
    helpText: "e.g., dominating conversations, difficulty stopping once started",
    clinicalThreshold: 3,
  },
  {
    id: "dsm5_b7",
    domain: "B",
    domainName: "Hyperactivity/Impulsivity",
    questionNumber: 22,
    text: "Blurting out answers before questions are finished",
    helpText: "e.g., finishing others' sentences, answering before fully hearing the question",
    clinicalThreshold: 3,
  },
  {
    id: "dsm5_b8",
    domain: "B",
    domainName: "Hyperactivity/Impulsivity",
    questionNumber: 23,
    text: "Having difficulty waiting your turn",
    helpText: "e.g., in queues, in meetings, in conversations",
    clinicalThreshold: 3,
  },
  {
    id: "dsm5_b9",
    domain: "B",
    domainName: "Hyperactivity/Impulsivity",
    questionNumber: 24,
    text: "Interrupting or intruding on others' conversations or activities",
    helpText: "e.g., butting into conversations, taking over tasks without being asked",
    clinicalThreshold: 3,
  },
  {
    id: "dsm5_b10",
    domain: "B",
    domainName: "Hyperactivity/Impulsivity",
    questionNumber: 25,
    text: "Making impulsive decisions without thinking through consequences",
    helpText: "e.g., unplanned purchases, quitting a job, ending relationships impulsively",
    clinicalThreshold: 3,
  },
  {
    id: "dsm5_b11",
    domain: "B",
    domainName: "Hyperactivity/Impulsivity",
    questionNumber: 26,
    text: "Losing your temper or getting frustrated quickly and disproportionately",
    helpText: "e.g., reacting strongly to minor inconveniences or criticism",
    clinicalThreshold: 3,
  },
  {
    id: "dsm5_b12",
    domain: "B",
    domainName: "Hyperactivity/Impulsivity",
    questionNumber: 27,
    text: "Taking risks or engaging in activities without considering potential harm",
    helpText: "e.g., reckless driving, risky financial decisions",
    clinicalThreshold: 3,
  },
  {
    id: "dsm5_b13",
    domain: "B",
    domainName: "Hyperactivity/Impulsivity",
    questionNumber: 28,
    text: "Starting new projects or activities impulsively, without planning",
    helpText: "e.g., enrolling in courses, starting businesses, taking on commitments spontaneously",
    clinicalThreshold: 3,
  },
  {
    id: "dsm5_b14",
    domain: "B",
    domainName: "Hyperactivity/Impulsivity",
    questionNumber: 29,
    text: "Having difficulty waiting for a reward or delayed outcome",
    helpText: "e.g., strong preference for immediate gratification, impatience with long-term goals",
    clinicalThreshold: 3,
  },
  {
    id: "dsm5_b15",
    domain: "B",
    domainName: "Hyperactivity/Impulsivity",
    questionNumber: 30,
    text: "Saying things you later regret without pausing to think first",
    helpText: "e.g., blurting out inappropriate or hurtful remarks impulsively",
    clinicalThreshold: 3,
  },
];
