"use client";

import { useRef, useReducer, type RefObject } from "react";
import { Download, Loader2 } from "lucide-react";

interface PDFDownloadButtonProps {
  targetRef: RefObject<HTMLDivElement | null>;
}

type State = { status: "idle" | "generating" | "slow" | "error" };

const DISCLAIMER =
  "This report is generated by fayth.life, an evidence-based ADHD screening tool. " +
  "It is NOT a clinical diagnosis. Please consult a qualified healthcare professional " +
  "for a formal evaluation and diagnosis.";

/** Inject compact styles for PDF capture, return cleanup function */
function injectPrintStyles(): () => void {
  const style = document.createElement("style");
  style.id = "pdf-print-styles";
  style.textContent = `
    [data-pdf-capture] {
      background: #ffffff !important;
      padding: 24px !important;
      font-size: 12px !important;
      line-height: 1.4 !important;
    }
    [data-pdf-capture] h1 {
      font-size: 20px !important;
      margin-bottom: 4px !important;
    }
    [data-pdf-capture] h2, [data-pdf-capture] h3 {
      font-size: 14px !important;
      margin-bottom: 4px !important;
    }
    [data-pdf-capture] .mb-8 { margin-bottom: 12px !important; }
    [data-pdf-capture] .mb-6 { margin-bottom: 8px !important; }
    [data-pdf-capture] .mb-5 { margin-bottom: 6px !important; }
    [data-pdf-capture] .mb-4 { margin-bottom: 4px !important; }
    [data-pdf-capture] .mb-3 { margin-bottom: 2px !important; }
    [data-pdf-capture] .gap-4 { gap: 6px !important; }
    [data-pdf-capture] .gap-3 { gap: 4px !important; }
    [data-pdf-capture] .space-y-4 > * + * { margin-top: 6px !important; }
    [data-pdf-capture] .space-y-3 > * + * { margin-top: 4px !important; }
    [data-pdf-capture] .p-5 { padding: 10px !important; }
    [data-pdf-capture] .p-4 { padding: 8px !important; }
    [data-pdf-capture] .py-12 { padding-top: 0 !important; padding-bottom: 0 !important; }
    /* Shrink charts so they don't dominate pages */
    [data-pdf-capture] .h-56 { height: 140px !important; }
    [data-pdf-capture] .h-52 { height: 130px !important; }
    [data-pdf-capture] .recharts-responsive-container { max-height: 140px !important; }
    /* Compact card borders/shadows */
    [data-pdf-capture] .rounded-2xl { border-radius: 10px !important; }
    [data-pdf-capture] .shadow-sm { box-shadow: 0 1px 2px rgba(0,0,0,0.05) !important; }
  `;
  document.head.appendChild(style);
  return () => style.remove();
}

export default function PDFDownloadButton({ targetRef }: PDFDownloadButtonProps) {
  const [state, setState] = useReducer((_: State, s: State) => s, { status: "idle" });
  const busyRef = useRef(false);

  const handleDownload = async () => {
    const element = targetRef.current;
    if (!element || busyRef.current) return;

    busyRef.current = true;
    setState({ status: "generating" });
    try {
      const { toCanvas } = await import("html-to-image");
      const { jsPDF } = await import("jspdf");

      const fileName = `adhd-screening-report-${new Date().toISOString().split("T")[0]}.pdf`;

      // Apply compact print styles and mark element for capture
      element.setAttribute("data-pdf-capture", "");
      const cleanupStyles = injectPrintStyles();

      // Let browser reflow with new styles
      await new Promise((r) => requestAnimationFrame(() => requestAnimationFrame(r)));

      const slowTimer = setTimeout(() => setState({ status: "slow" }), 10_000);
      const canvas = await Promise.race([
        toCanvas(element, {
          pixelRatio: 2,
          cacheBust: true,
          skipFonts: true,
          backgroundColor: "#ffffff",
        }),
        new Promise<never>((_, reject) =>
          setTimeout(() => reject(new Error("PDF generation timed out")), 30_000)
        ),
      ]);
      clearTimeout(slowTimer);

      // Restore original styles immediately
      element.removeAttribute("data-pdf-capture");
      cleanupStyles();

      const pdf = new jsPDF({ unit: "mm", format: "a4", orientation: "portrait" });

      const margin = 12;
      const headerH = 6;
      const disclaimerH = 8;
      const pageW = pdf.internal.pageSize.getWidth();
      const pageH = pdf.internal.pageSize.getHeight();
      const contentW = pageW - margin * 2;
      const contentH = pageH - margin * 2 - headerH - disclaimerH;

      const scale = contentW / canvas.width;
      const sliceHeightPx = Math.floor(contentH / scale);
      const totalPages = Math.ceil(canvas.height / sliceHeightPx);

      for (let page = 0; page < totalPages; page++) {
        if (page > 0) pdf.addPage();

        // Header
        pdf.setFontSize(8);
        pdf.setTextColor(120, 120, 120);
        pdf.text("fayth.life — ADHD Screening Report", margin, margin);
        pdf.text(
          page === 0
            ? new Date().toLocaleDateString()
            : `Page ${page + 1} of ${totalPages}`,
          pageW - margin,
          margin,
          { align: "right" }
        );

        // Slice this page's chunk from the full canvas
        const sy = page * sliceHeightPx;
        const sh = Math.min(sliceHeightPx, canvas.height - sy);
        const sliceCanvas = document.createElement("canvas");
        sliceCanvas.width = canvas.width;
        sliceCanvas.height = sh;
        const ctx = sliceCanvas.getContext("2d");
        if (ctx) {
          ctx.fillStyle = "#ffffff";
          ctx.fillRect(0, 0, sliceCanvas.width, sliceCanvas.height);
          ctx.drawImage(canvas, 0, sy, canvas.width, sh, 0, 0, canvas.width, sh);
        }

        const sliceData = sliceCanvas.toDataURL("image/jpeg", 0.95);
        const sliceH = sh * scale;
        pdf.addImage(sliceData, "JPEG", margin, margin + headerH, contentW, sliceH);

        // Disclaimer footer
        pdf.setFontSize(6.5);
        pdf.setTextColor(150, 150, 150);
        const lines = pdf.splitTextToSize(DISCLAIMER, contentW);
        pdf.text(lines, margin, pageH - margin);
      }

      pdf.save(fileName);
      setState({ status: "idle" });
    } catch (err) {
      console.error("PDF generation failed:", err);
      setState({ status: "error" });
    } finally {
      busyRef.current = false;
    }
  };

  const generating = state.status === "generating" || state.status === "slow";

  return (
    <div>
      <button
        type="button"
        onClick={handleDownload}
        className={`inline-flex items-center justify-center rounded-xl font-medium px-6 py-3 text-base min-h-[44px] bg-[#fbbf24] text-foreground border-2 border-foreground shadow-[3px_3px_0_#1a2410] hover:shadow-[4px_4px_0_#1a2410] hover:-translate-x-px hover:-translate-y-px active:shadow-[1px_1px_0_#1a2410] active:translate-x-0.5 active:translate-y-0.5 transition-all duration-150 cursor-pointer${generating ? " opacity-50" : ""}`}
      >
        {generating ? (
          <Loader2 size={16} className="mr-2 animate-spin" />
        ) : (
          <Download size={16} className="mr-2" />
        )}
        {state.status === "slow" ? "Still generating..." : generating ? "Generating PDF..." : "Download Report (PDF)"}
      </button>
      {state.status === "slow" && (
        <p className="text-amber-600 text-sm mt-2">This is taking longer than expected...</p>
      )}
      {state.status === "error" && (
        <p className="text-red-600 text-sm mt-2">PDF generation failed. Please try again.</p>
      )}
    </div>
  );
}
