#!/usr/bin/env python3
"""
ADHD Screening Report Exporter

Fetches questionnaire results from Supabase (via the Next.js API route)
and generates a formatted PDF report.

Usage:
  python export_report.py <session_id> [--include-games] [--output report.pdf]

Requirements:
  pip install requests fpdf2

Environment variables:
  REPORT_API_URL  — Base URL of the deployed app (e.g. https://your-app.vercel.app)
"""

import argparse
import json
import sys
from datetime import datetime

try:
    import requests
except ImportError:
    print("ERROR: 'requests' not installed. Run: pip install requests")
    sys.exit(1)

try:
    from fpdf import FPDF
except ImportError:
    print("ERROR: 'fpdf2' not installed. Run: pip install fpdf2")
    sys.exit(1)

import os

DEFAULT_API_URL = os.environ.get("REPORT_API_URL", "http://localhost:3000")


def fetch_report(session_id: str, include_games: bool = False) -> dict:
    """Fetch the questionnaire result JSON from the API route."""
    url = f"{DEFAULT_API_URL}/api/report/{session_id}"
    if include_games:
        url += "?include=games"

    resp = requests.get(url, timeout=15)
    if resp.status_code == 404:
        print(f"No questionnaire result found for session: {session_id}")
        sys.exit(1)
    resp.raise_for_status()
    return resp.json()


class ReportPDF(FPDF):
    """Custom PDF layout for ADHD screening reports."""

    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.cell(0, 10, "ADHD Screening Report", ln=True, align="C")
        self.set_font("Helvetica", "", 9)
        self.cell(0, 6, "Generated by Fayth.life", ln=True, align="C")
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 13)
        self.set_fill_color(240, 240, 245)
        self.cell(0, 10, f"  {title}", ln=True, fill=True)
        self.ln(3)

    def key_value(self, key: str, value: str):
        self.set_font("Helvetica", "B", 10)
        self.cell(65, 7, key + ":")
        self.set_font("Helvetica", "", 10)
        self.multi_cell(0, 7, str(value))

    def spacer(self, h: int = 5):
        self.ln(h)


def build_pdf(data: dict, output_path: str):
    """Build a PDF from the API response data."""
    q = data["questionnaire"]
    user_data = q.get("user_data", {})
    interpretation = q.get("interpretation", {})

    pdf = ReportPDF()
    pdf.alias_nb_pages()
    pdf.add_page()

    # --- Patient Info ---
    pdf.section_title("Patient Information")
    pdf.key_value("Name", user_data.get("name", "Anonymous"))
    pdf.key_value("Age", str(user_data.get("age", "N/A")))
    pdf.key_value("Gender", str(user_data.get("gender", "N/A")))
    if user_data.get("email"):
        pdf.key_value("Email", user_data["email"])
    pdf.key_value("Session ID", data.get("session_id", "N/A"))
    completed = q.get("completed_at", "")
    if completed:
        try:
            dt = datetime.fromisoformat(completed.replace("Z", "+00:00"))
            pdf.key_value("Completed", dt.strftime("%B %d, %Y at %I:%M %p"))
        except ValueError:
            pdf.key_value("Completed", completed)
    pdf.spacer()

    # --- Instrument & Scores ---
    instrument = q.get("instrument", "unknown").upper()
    pdf.section_title(f"Instrument: {instrument}")
    pdf.key_value("Domain A Score", f"{q.get('domain_a_score', 'N/A')} (total: {q.get('domain_a_total', 'N/A')})")
    pdf.key_value("Domain B Score", f"{q.get('domain_b_score', 'N/A')} (total: {q.get('domain_b_total', 'N/A')})")
    pdf.key_value("Presentation Type", str(q.get("presentation_type", "N/A")))
    pdf.key_value("Risk Level", str(q.get("risk_level", "N/A")))
    pdf.spacer()

    # DSM-5 criteria
    if q.get("meets_symptom_threshold") is not None:
        pdf.section_title("DSM-5 Criteria")
        pdf.key_value("Meets Symptom Threshold", "Yes" if q["meets_symptom_threshold"] else "No")
        pdf.key_value("Multiple Settings", "Yes" if q.get("multiple_settings") else "No")
        pdf.key_value("Before Age 12", "Yes" if q.get("before_age_12") else "No")
        pdf.key_value("Significant Impact", "Yes" if q.get("significant_impact") else "No")
        pdf.spacer()

    # ASRS-specific
    if q.get("part_a_shaded_count") is not None:
        pdf.section_title("ASRS Part A")
        pdf.key_value("Part A Shaded Count", str(q["part_a_shaded_count"]))
        pdf.key_value("Part A High Risk", "Yes" if q.get("part_a_high_risk") else "No")
        pdf.spacer()

    # --- Interpretation ---
    if interpretation:
        pdf.section_title("Clinical Interpretation")
        if interpretation.get("clinicalNote"):
            pdf.set_font("Helvetica", "", 10)
            pdf.multi_cell(0, 6, interpretation["clinicalNote"])
            pdf.spacer()
        if interpretation.get("genderInsights"):
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 7, "Gender-Specific Insights:", ln=True)
            pdf.set_font("Helvetica", "", 10)
            for insight in interpretation["genderInsights"]:
                pdf.cell(8)
                pdf.multi_cell(0, 6, f"- {insight}")
            pdf.spacer()
        if interpretation.get("recommendations"):
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 7, "Recommendations:", ln=True)
            pdf.set_font("Helvetica", "", 10)
            for rec in interpretation["recommendations"]:
                pdf.cell(8)
                pdf.multi_cell(0, 6, f"- {rec}")
            pdf.spacer()

    # --- Individual Responses ---
    responses = q.get("responses")
    if responses and isinstance(responses, dict):
        pdf.section_title("Individual Responses")
        likert_labels = {0: "Never", 1: "Rarely", 2: "Sometimes", 3: "Often", 4: "Very Often"}
        pdf.set_font("Helvetica", "", 9)
        for qid, val in sorted(responses.items()):
            label = likert_labels.get(val, str(val))
            pdf.cell(35, 6, qid)
            pdf.cell(0, 6, f"{label} ({val})", ln=True)
        pdf.spacer()

    # --- Game Scores ---
    games = data.get("games")
    if games:
        for game_name, game_data in games.items():
            if game_data:
                pdf.section_title(f"Game: {game_name}")
                pdf.set_font("Helvetica", "", 9)
                pdf.multi_cell(0, 6, json.dumps(game_data, indent=2, default=str))
                pdf.spacer()

    # --- Disclaimer ---
    pdf.spacer(10)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(128, 128, 128)
    pdf.multi_cell(
        0, 5,
        "DISCLAIMER: This report is for informational and screening purposes only. "
        "It is not a clinical diagnosis. Please consult a qualified healthcare professional "
        "for any medical or psychological concerns.",
    )

    pdf.output(output_path)
    print(f"PDF saved to: {output_path}")


def export_json(data: dict, output_path: str):
    """Save the raw JSON data to a file."""
    json_path = output_path.rsplit(".", 1)[0] + ".json"
    with open(json_path, "w") as f:
        json.dump(data, f, indent=2, default=str)
    print(f"JSON saved to: {json_path}")


def main():
    parser = argparse.ArgumentParser(description="Export ADHD screening report as PDF")
    parser.add_argument("session_id", help="The session ID to export")
    parser.add_argument("--include-games", action="store_true", help="Include game scores in report")
    parser.add_argument("--output", "-o", default=None, help="Output PDF file path")
    parser.add_argument("--json", action="store_true", help="Also save raw JSON data")
    parser.add_argument("--api-url", default=None, help="Override API base URL")
    args = parser.parse_args()

    if args.api_url:
        global DEFAULT_API_URL
        DEFAULT_API_URL = args.api_url

    output = args.output or f"adhd-report-{args.session_id[:8]}.pdf"

    print(f"Fetching report for session: {args.session_id}")
    data = fetch_report(args.session_id, args.include_games)

    if args.json:
        export_json(data, output)

    build_pdf(data, output)


if __name__ == "__main__":
    main()
